name: Inject and Deploy API Key

on:
  push:
    branches:
      - main

jobs:
  inject-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare API Keys
        id: prep-keys
        run: |
          # Limpia saltos de línea y espacios al principio/final de las claves
          YOUTUBE_KEY=$(echo "${{ secrets.YOUTUBE_API_KEY }}" | tr -d '\n' | xargs)
          GOOGLE_DRIVE_KEY=$(echo "${{ secrets.GOOGLE_DRIVE_API_KEY }}" | tr -d '\n' | xargs)
          echo "::set-output name=YOUTUBE_KEY::$YOUTUBE_KEY"
          echo "::set-output name=GOOGLE_DRIVE_KEY::$GOOGLE_DRIVE_KEY"

      - name: Inject API Keys into HTML
        run: |
          # Reemplaza los placeholders en todos los archivos que los necesitan
          # Usando el símbolo '@' como separador, es muy raro que esté en una clave API
          sed -i "s@TU_CLAVE_DE_API_YOUTUBE@${{ steps.prep-keys.outputs.YOUTUBE_KEY }}@g" index.html
          sed -i "s@TU_CLAVE_DE_API_GOOGLE_DRIVE@${{ steps.prep-keys.outputs.GOOGLE_DRIVE_KEY }}@g" index.html
          sed -i "s@TU_CLAVE_DE_API_YOUTUBE@${{ steps.prep-keys.outputs.YOUTUBE_KEY }}@g" discorgafia.html
          sed -i "s@TU_CLAVE_DE_API_YOUTUBE@${{ steps.prep-keys.outputs.YOUTUBE_KEY }}@g" movie.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: false
