name: Deploy Tenshi Website

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Inyectar API key en todos los HTML
      - name: Inject YouTube API key
        run: |
          find . -type f -name "*.html" -exec sed -i "s|TU_CLAVE_DE_API|${{ secrets.TU_CLAVE_DE_API }}|g" {} +

      # 3️⃣ Deploy a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .   # Si tu HTML está en la raíz del repo
