name: Inject and Deploy API Key

on:
  push:
    branches:
      - main

jobs:
  inject-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject API Keys into HTML
        run: |
          # Reemplaza los placeholders con las claves reales
          sed -i "s|TU_CLAVE_DE_API_YOUTUBE|${{ secrets.YOUTUBE_API_KEY }}|g" mi-sitio-web.html
          sed -i "s|TU_CLAVE_DE_API_GOOGLE_DRIVE|${{ secrets.GOOGLE_DRIVE_API_KEY }}|g" mi-sitio-web.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: false
