name: Deploy Tenshi Website

on: 
  push: 
    branches:
      - main

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Traer tu página
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Checar que la clave existe
      - name: Check YouTube API key
        run: |
          if [ -z "${{ secrets.YOUTUBE_API_KEY }}" ]; then
            echo "Error: La clave no está."
            exit 1
          else
            echo "Clave encontrada (larga como debe ser)."
          fi

      # 3. Ver cómo está antes
      - name: Debug before injection
        run: |
          echo "Archivos antes:"
          find . -type f -name "*.html" -exec cat {} \;

      # 4. Poner la clave en los archivos
      - name: Inject YouTube API key
        run: |
          echo "Poniendo la clave..."
          find . -type f -name "*.html" -exec sed -i "s|TU_CLAVE_DE_API|${{ secrets.YOUTUBE_API_KEY }}|g" {} \;
          if [ $? -ne 0 ]; then
            echo "Error al poner la clave."
            exit 1
          fi
          echo "Checando..."
          if ! find . -type f -name "*.html" -exec grep "${{ secrets.YOUTUBE_API_KEY }}" {} +; then
            echo "Clave no entró en algún archivo."
            exit 1
          fi

      # 5. Ver cómo quedó después
      - name: Debug after injection
        run: |
          echo "Archivos después:"
          find . -type f -name "*.html" -exec cat {} \;

      # 6. Subir la página
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
