name: Inject and Deploy API Key

on: 
  push: 
    branches:
      - main

jobs:
  inject-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject API Key into HTML
        run: |
          sed -i 's|TU_CLAVE_DE_API|${{ secrets.YOUTUBE_API_KEY }}|g' mi-sitio-web.html movie.html Discography.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
