name: Inject and Deploy API Key (YouTube Only)

on:
  push:
    branches:
      - main

jobs:
  inject-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Usamos v4 por ser la última versión

      - name: Inject YouTube API Key into HTML
        run: |
          # Reemplaza el placeholder de YouTube en todos los archivos
          sed -i 's|TU_CLAVE_DE_API_YOUTUBE|${{ secrets.YOUTUBE_API_KEY }}|g' index.html
          sed -i 's|TU_CLAVE_DE_API_YOUTUBE|${{ secrets.YOUTUBE_API_KEY }}|g' discorgafia.html
          sed -i 's|TU_CLAVE_DE_API_YOUTUBE|${{ secrets.YOUTUBE_API_KEY }}|g' movie.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: false
