name: Render catálogo bonito

on:
  push:
    paths:
      - "data/catalogo.json"
      - "scripts/render-catalogo.js"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generar CATALOGO.md
        run: node scripts/render-catalogo.js

      - name: Commit & push si hubo cambios
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: actualizar CATALOGO.md desde catalogo.json"
          file_pattern: CATALOGO.md
